name = input("What is your name? ")
current_role = input("What is your current role? ")
dream_role = input("What is your dream role? ")
years_until_goal = int(input("How many years until you reach your dream role? "))

print("\n" + "=" * 32)
print("Career Roadmap")
print("=" * 32)
print(f"\nWelcome {name}!")
print()
print(f"Current Role: {current_role}")
print(f"Dream Role: {dream_role}")
print(f"Timeline: {years_until_goal} Years")
print()
print("Let's build your future!")
print("=" * 32)