services:

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: employees
      DATABASE_USER: employee_user
      DATABASE_PASSWORD: employee_password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17

    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee_user -d employees"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-data: